# Generated by Django 5.0.1 on 2024-01-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_hire_customer_hire_photographer'),
        ('service_provider', '0008_photographer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='price',
        ),
        migrations.AddField(
            model_name='hire',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_provider.services'),
            preserve_default=False,
        ),
    ]
