# Generated by Django 5.0.1 on 2024-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_hire_customer_alter_hire_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
    ]
