# Generated by Django 5.0 on 2024-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_hire_status_alter_testimonial_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Hired', 'Hired'), ('Not Hired', 'Not Hired'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
    ]
