# Generated by Django 5.0.1 on 2024-01-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_provider.photographer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_provider.photographer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_provider.photographer'),
            preserve_default=False,
        ),
    ]
