# Generated by Django 5.0.1 on 2024-01-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='image',
            field=models.ImageField(null='True', upload_to='photographers'),
            preserve_default='True',
        ),
    ]
