# Generated by Django 5.0.1 on 2024-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_photographer_is_videograher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='photographer',
            old_name='is_videograher',
            new_name='is_videographer',
        ),
        migrations.AddField(
            model_name='photographer',
            name='tags',
            field=models.ManyToManyField(to='service_provider.tag'),
        ),
    ]
