# Generated by Django 5.0.1 on 2024-02-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0012_alter_photographer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='type',
        ),
    ]
