# Generated by Django 5.0.1 on 2024-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0012_alter_photographer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Busy', 'Busy')], default=1, max_length=254),
            preserve_default=False,
        ),
    ]
