# Generated by Django 5.0.1 on 2024-01-17 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('service_provider', '0002_equipment_photographer_photo_photographer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_provider.photographer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_provider.photographer'),
            preserve_default=False,
        ),
    ]
