# Generated by Django 5.0.1 on 2024-03-03 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_feedback_created_at_alter_feedback_customer'),
        ('management', '0009_alter_hire_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.hire'),
        ),
    ]
