# Generated by Django 5.0.1 on 2024-01-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Information',
        ),
    ]
