# Generated by Django 5.0.1 on 2024-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
