# Generated by Django 5.0.1 on 2024-01-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_about_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
    ]
