# Generated by Django 5.0.1 on 2024-01-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_about_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='name',
        ),
    ]
